### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'page'

### ISSUE THREAD

**Issue by tikitong** [Krasjet/pdf.tocgen#16]
Hi, Thank you for this great work! 

I'm looking to detect and extract pdf TOC, but all my tests (with short or long and complex pdf) raise the following error: `ValueError: invalid literal for int() with base 10: 'page'`. 

For example with this one: https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/text-extraction/Dart.pdf or [this one](https://drive.google.com/file/d/1gVX0HjWZ7OmLvWrFCFgaj44oj5cMXcfX/view?usp=sharing) (not a LaTex file). 
```
(pdftocgen) user@MacBook-Pro-de-user Desktop % pdfxmeta -p page -a 1 Dart.pdf "Section" >> recipe.toml   
Traceback (most recent call last):
  File "/Users/user/miniconda3/envs/pdftocgen/bin/pdfxmeta", line 8, in <module>
    sys.exit(main())
  File "/Users/user/miniconda3/envs/pdftocgen/lib/python3.9/site-packages/pdfxmeta/app.py", line 91, in main
    page = int(a)
ValueError: invalid literal for int() with base 10: 'page'
```
I am on macOS and the installation of `pdf.tocgen` with the command `pip install -U pdf.tocgen` worked well (I detailed the way [here](https://github.com/pymupdf/PyMuPDF/issues/2012#issue-1432256653)). 
 
Do you know why this error is raised? Thanks again.

**Comment by Krasjet** [comment]
`page` is supposed to be replaced with a page number. and `"Section"` should be replaced by part of a section title. Try
```console
$ pdfxmeta -p 1 -a 1 Dart.pdf "Scope"
```
