### ISSUE TITLE
ToC Positioning Accuracy

### ISSUE THREAD

**Issue by sun2ot** [Krasjet/pdf.tocgen#17]
First, thanks to your project! It is very useful! But I have a little question about the positioning accuracy of ToC.

Generated titles seem to be specific to one page, not to a position within a page. This will cause if my title is at the end of a page, I can't jump to the title after clicking ToC, but need to keep scrolling down to find it. And if my multiple headers are on the same page, when I click on the ToC, the page doesn't even change anything.

Also I found that the headers added manually by the PDF reader don't have this problem.

Hope to your reply. Thank you!

**Comment by Iey4iej3** [comment]
This is achieved by the `-v` option of `pdftocgen`, cf. https://krasjet.com/voice/pdf.tocgen
