### ISSUE TITLE
Combining characters

### ISSUE THREAD

**Issue by lucasvreis** [Krasjet/pdf.tocgen#19]
It seems pdftocgen does not support unicode combining characters (like most diacritical marks), and since they are very common in most non-English languages I think it would be nice to support them. Other tools like `pdftotext` and `evince` can handle such characters correctly, so I think this is not an issue with the PDF files themselves.

Example: [t1.pdf](https://github.com/Krasjet/pdf.tocgen/files/11313098/t1.pdf)
`pdftotext t1.pdf` prints `Matemática`, but `pdfxmeta t1.pdf` prints:
```
Matem´atica:
    font.name = "CMBX12"
    font.size = 14.346199989318848
    font.color = 0x000000
    [...]
```

**Comment by Krasjet** [comment]
This is a problem in the MuPDF library used by pdf.tocgen. You can reproduce the same problem in zathura by copying the text.
![zathura](https://user-images.githubusercontent.com/5229241/234143337-a6d86cb3-ad7b-4c7f-ab75-f853575692c2.png)

Basically this is what you get using the text extraction interface of PyMuPDF
```python
>>> import fitz
>>> doc = fitz.open("t1.pdf")
>>> doc[0].get_text()
'1\nMatem´atica\n1\n'
```

I think it's more appropriate to report the bug to the MuPDF team. https://bugs.ghostscript.com/buglist.cgi?component=mupdf&product=MuPDF&resolution=---
