### ISSUE TITLE
[feature request] Make this into one script

### ISSUE THREAD

**Issue by lzh01** [Krasjet/pdf.tocgen#20]
This is a lovely tool and works perfectly.  It would be even easy to use if we can link them all together with one script.

This script might run with arguments: 
 - filename
 - [(page, string)] to search the xmeta.

and with interactive:
- confirm the generated toc
- open the generated pdf file to further check.
- maybe also confirm the output file path.

**Comment by Krasjet** [comment]
Someone actually did put this together, just a few lines of shell scripts: https://github.com/Ladbaby/TOC_PDF/

**Comment by lzh01** [comment]
Thanks, played a little bit, that script works (though not that user friendly).

Still would nice to have it in the package (even better if this can be a python script so no need worry about the shell).
