### ISSUE TITLE
"KeyError: 'to'" when extracting ToC from some PDFs with pdftocio

### ISSUE THREAD

**Issue by outis** [Krasjet/pdf.tocgen#22]
## Synopsis
When using pdftocio to extract a table of contents, it sometimes crashes with the error "KeyError: 'to'".

## Steps to Reproduce
1. Create a PDF (named e.g. "toc.pdf") with an outline item (AKA bookmark) that fits the entire page to the view (I'm not certain of the terminology here; the PDF standard doesn't seem to define any special term for this; the Destination syntax has names, such as `/Fit` and `/XYZ`, that specify how the page is to be displayed but doesn't define a term for these names or the behavior they specify).
2. Use pdftocio to extract the ToC from the PDF, (e.g. run `pdftocio toc.pdf`)

## Expected Result
A table of contents (in the format used by pdf.tocgen) should be output.

## Actual Result
pdftocio outputs a stack trace and an error:
```
 Traceback (most recent call last):
  File "/usr/local/bin/pdftocio", line 8, in <module>
    sys.exit(main())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pdftocio/app.py", line 142, in main
    toc = read_toc(doc)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pdftocio/tocio.py", line 16, in read_toc
    return [
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pdftocio/tocio.py", line 17, in <listcomp>
    ToCEntry(e[0], e[1], e[2], e[3]['to'].y) if len(e) == 4 else
KeyError: 'to'
```

## Additional Info
A [minimal sample PDF](https://github.com/Krasjet/pdf.tocgen/files/12248194/toc.pdf) was created containing a single bookmark with the view fit set to "Page" (`/Fit`. This causes pdftocio to generate the above error. Printing the value of `e` that causes the exception gives:
```
[1, 'Page', 1, {'kind': 4, 'xref': 2, 'name': 'page=1&view=Fit', 'zoom': 0.0}]
```

For comparison, this is the entry for a bookmark created by pdftocio (a fit of `/XYZ`, fit top-left and zoom):
```
[[1, 'Page', 1, {'kind': 1, 'xref': 2, 'page': 0, 'to': Point(0.0, 0.0), 'zoom': 0.7222222089767456}]]
```

Other fits also cause this error: `/FitH` (fit width), `/FitV` (fit height), '/FitR' (fit rectangle). I wasn't able to test the bounding box fits, `/FitB`, `/FitBH` and `/FitBV`.

Looking at the function containing the line where the error is generated (`read_toc`), it tests whether `e` has 4 entries (to avoid an exception), but it assumes that if the 4th entry is present, it will be an object containing a "to" key. However, fitz (which provides the method, `fitz.Document.get_toc`, used to generate `e`) doesn't seem to create this key except when the fit is `/XYZ`. This last might be a bug within fitz, but it still can and should be addressed in pdftocio. Is expanding the test to check whether the key is present (`len(e) == 4 and "to" in e`) sufficient, or will there be some other problem if `e[3]` exists but doesn't contain a "to" item?

Long term, supporting different fits might be the best solution (and a nice new feature), as this would both allow preserving them for an existing ToC and allow users to set them.

**Comment by jdhoek** [comment]
Your commit solves this error for me (I just patched my local version using an editor), but it doesn't seem to be included in the version on PyPI yet. Is that correct?
