### ISSUE TITLE
multiline headings can't be merged

### ISSUE THREAD

**Issue by Zane-XY** [Krasjet/pdf.tocgen#29]
The expected output for below configuration is to generate `Chapter 1: Introduction" as one heading, but it generates as two separate headings pointing to the same page.

```
[[heading]]
# Chapter 1
level = 1
greedy = true
font.name = "ComputerModernBoldExtend"
font.size = 24.875999450683594

[[heading]]
# Introduction
level = 1
greedy = true
font.name = "ComputerModernBoldExtend"
font.size = 29.844999313354492

```
It should merge the headings at the same level, right? Or maybe we should allow to specify a heading pattern regex.

**Comment by Krasjet** [comment]
It should be the problem of the pdf. The headings needs to belong to the same span to be merged. You need to manually fix the ToC in this case.
