### ISSUE TITLE
Couldn't read the doc in my current dir, please help

### ISSUE THREAD

**Issue by yuw444** [Krasjet/pdf.tocgen#3]
Hi, 

I'm using Python3.8, and here is my code: 

    import pdfxmeta
    import pdftocgen
    import pdftocio

    pdfxmeta -p 14 onlisp.pdf "The Extensible"

Error message:
````
"C:\Users\Yu Wang\Python3.8\python.exe" "C:/Users/Yu Wang/PycharmProjects/pythonProject/main.py"
  File "C:/Users/Yu Wang/PycharmProjects/pythonProject/main.py", line 6
    pdfxmeta -p 14 onlisp.pdf "The Extensible"
                ^
SyntaxError: invalid syntax

````

Here is my current dictionary:

````
os.getcwd()
'C:\\Users\\Yu Wang\\PycharmProjects\\pythonProject'
````
My file path is "C:\\Users\\Yu Wang\\PycharmProjects\\pythonProject\\onlisp.pdf"

Please help!

Thanks so much!

Best Regards,
Yu Wang

**Comment by Krasjet** [comment]
You need to run the command in a shell, not in Python.

**Comment by yuw444** [comment]
Thanks for your quick feedback. I'm a relatively new user to Python, not familiar with Shell command and only did in Python. Any suggestions about what topic I should look into? 

Thanks.

**Comment by Krasjet** [comment]
If you are on Windows, press `Win + R` and run [`cmd`][1] to open the shell. If you install `pdf.tocgen` correctly using [`pip`][2], you should see something like this when you execute `pdftocgen`:
```console
> pdftocgen
error: no input pdf is given
usage: pdftocgen [options] doc.pdf < recipe.toml
```
Then you should have no problem following the tutorial.

If not, check your [`PATH`][3] variable and make sure the `Scripts` directory of your Python installation is present.

Alternatively, if you are using Git on Windows, [`Git Bash`][4] might also work, but I have never tried it.

[1]: https://en.wikipedia.org/wiki/Cmd.exe
[2]: https://pip.pypa.io/en/stable/installing/
[3]: https://en.wikipedia.org/wiki/PATH_(variable)
[4]: https://gitforwindows.org/

**Comment by yuw444** [comment]
Thanks so much for your help, it turn out my `pdf.tocgen`  install in a different folder as I forgot to type `-U` in `pip install -U pdf.tocgen`. Then I followed along the example well afterwards. 

Another question, it seems it couldn't detect the **Chapter \#** in the example. I tried to add `1. The Extensible` in the `level 1` with no luck. Any comments?

Thanks!

**Comment by yuw444** [comment]
Okay, I see. I can edit `toml` and `toc` file directly, which is why you partitioned this algorithm into 3 steps. We can manually change them as needed. What a brilliant idea!

Thanks
