### ISSUE TITLE
How did you build the homepage?

### ISSUE THREAD

**Issue by AIboy996** [Krasjet/pdf.tocgen#35]
I mean : https://krasjet.com/voice/pdf.tocgen/

It very cool and looks like you built it automaiclly from some kind of source file like `.ipynb`.

thanks a lot

**Comment by Krasjet** [comment]
https://github.com/Krasjet/fl.tr/blob/ebe56141487bdb32d35fa2f4077be1364c2c808f/src/Text/Pandoc/Fltr/ReplFilter.hs
