### ISSUE TITLE
Error with pdftocio

### ISSUE THREAD

**Issue by meriops** [Krasjet/pdf.tocgen#4]
I get an error when trying to insert the toc generated by pdftocgen into the pdf with pdftocio... I wonder if it has to do with your warning "don't expect it to work with scanned pdfs" (although the toc generation worked perfectly) or if it is something else... Below is the traceback. 

Traceback (most recent call last):

  File "/usr/bin/pdftocio", line 33, in <module>
    sys.exit(load_entry_point('pdf.tocgen==1.2.2', 'console_scripts', 'pdftocio')())
  File "/usr/lib/python3.9/site-packages/pdftocio/app.py", line 147, in main
    write_toc(doc, toc)
  File "/usr/lib/python3.9/site-packages/pdftocio/tocio.py", line 11, in write_toc
    doc.setToC(fitz_toc)
  File "/usr/lib/python3.9/site-packages/fitz/utils.py", line 1107, in setToC
    doc._updateObject(xref[i], txt)  # insert the PDF object
AttributeError: 'Document' object has no attribute '_updateObject'
zsh: exit 1     pdftocio -t toc book.pdf

**Comment by Krasjet** [comment]
This seems to be a bug in the latest version of PyMuPDF. You can try to downgrade it to 1.8.4 or below for now.

I have reported the bug to https://github.com/pymupdf/PyMuPDF/issues/779. Hopefully they will take a look at it soon.

**Comment by Krasjet** [comment]
This issue should be fixed if you upgrade PyMuPDF to the latest 1.18.6
