### ISSUE TITLE
error: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by nanjigen** [Krasjet/pdf.tocgen#5]
Thanks for the awesome project!

While this works very well after some tweaking of the toc for most documents, I am having trouble re-writing the toc for a fairly large pdf (no starch press's Python Crash Course)

I get the following error when running `pdftocio pythoncrashcourse_updated.pdf < toc`

`error: invalid literal for int() with base 10: ''`

This seems to indicate that there is a number somewhere (possibly a page number) being read as a string. I've quiet  carefully gone through the document but can't seem to find the issue. The error is also not particularly verbose.

**Comment by Krasjet** [comment]
Can you run with the `-g` option to show the full crash report?

**Comment by nanjigen** [comment]
`pdftocio -g wickedcoolshellscripts.pdf < toc`

```
[user@pc books]$ pdftocio -g wickedcoolshellscripts.pdf < toc
Traceback (most recent call last):
  File "/usr/bin/pdftocio", line 33, in <module>
    sys.exit(load_entry_point('pdf.tocgen==1.2.3', 'console_scripts', 'pdftocio')())
  File "/usr/lib/python3.9/site-packages/pdftocio/app.py", line 156, in main
    raise e
  File "/usr/lib/python3.9/site-packages/pdftocio/app.py", line 146, in main
    toc = parse_toc(toc_file)
  File "/usr/lib/python3.9/site-packages/pdftocio/tocparser.py", line 38, in parse_toc
    return list(map(parse_entry, reader))
  File "/usr/lib/python3.9/site-packages/pdftocio/tocparser.py", line 22, in parse_entry
    int(entry[indent + 1]),  # pagenum
ValueError: invalid literal for int() with base 10: ''

```

[toc.txt](https://github.com/Krasjet/pdf.tocgen/files/5936420/toc.txt)
(note that I added the `.txt` extension to the `toc` file to allow for attaching.)

**Comment by Krasjet** [comment]
hmm, there should be exactly one space between a heading and its page number. Maybe I will add a proper parser for the toc format some day.

This problem can be solved by
```console
$ sed -E 's/"\s+([0-9]+)/" \1/g' toc > toc_new
```
A fixed toc can be found at [toc_new](https://github.com/Krasjet/pdf.tocgen/files/5937607/toc.txt)

**Comment by nanjigen** [comment]
Thanks @Krasjet that fixes it for me
