### ISSUE TITLE
ValueError: could not convert string to float: 

### ISSUE THREAD

**Issue by nanjigen** [Krasjet/pdf.tocgen#6]
Hi @Krasjet, I'm having another error with issue with the `tocparser`. When attempting to generate the toc with `pdftocio -g higginbotham2015.pdf < toc` I get the following error:

```
Traceback (most recent call last):
  File "/usr/bin/pdftocio", line 33, in <module>
    sys.exit(load_entry_point('pdf.tocgen==1.2.3', 'console_scripts', 'pdftocio')())
  File "/usr/lib/python3.9/site-packages/pdftocio/app.py", line 156, in main
    raise e
  File "/usr/lib/python3.9/site-packages/pdftocio/app.py", line 146, in main
    toc = parse_toc(toc_file)
  File "/usr/lib/python3.9/site-packages/pdftocio/tocparser.py", line 38, in parse_toc
    return list(map(parse_entry, reader))
ValueError: could not convert string to float: 'Brief'
```
Obviously the error is pointing to the first word of the first line. I checked that I am using unix formatting by running `dos2unix` just in case something was hidden in the text file, but it didn't help.

[toc.txt](https://github.com/Krasjet/pdf.tocgen/files/6040189/toc.txt)

**Comment by Krasjet** [comment]
`pdftocio` is only intended to be used with the `toc` file generated from `pdftocgen`.

In particular, the titles should be double-quoted to distinguish titles from page numbers and vertical positions. If you are using `pdf.tocgen` only for `pdftocio`, there are probably better alternatives.

```
"Preface" 5
    "Bottom-up Design" 5
    "Plan of the Book" 7
    "Examples" 9
    "Acknowledgements" 9
"Contents" 11
"The Extensible Language" 14
    "1.1 Design by Evolution" 14
    "1.2 Programming Bottom-Up" 16
    "1.3 Extensible Software" 18
    "1.4 Extending Lisp" 19
    "1.5 Why Lisp (or When)" 21
"Functions" 22
    "2.1 Functions as Data" 22
    "2.2 Defining Functions" 23
    "2.3 Functional Arguments" 26
    "2.4 Functions as Properties" 28
```

**Comment by mrfragger** [comment]
pdfxmeta -a 1 -p 80 some.pdf "some term" > recipe.toml
 pdftocio some.pdf < recipe.toml > toc.toml
error: could not convert string to float: '[[heading]]'

perhaps it's due to python 13 ..no clue

this is what the reciple.toml looks like

```
[[heading]]
level = 1
greedy = true
font.name = "Times New Roman,Bold"
font.size = 24.0
# font.size_tolerance = 1e-5
# font.color = -0x1000000
# font.superscript = false
# font.italic = false
# font.serif = true
# font.monospace = false
# font.bold = true
# bbox.left = 72.02400207519531
# bbox.top = 69.28402709960938
# bbox.right = 529.365966796875
# bbox.bottom = 102.5240249633789
# bbox.tolerance = 1e-5

```
