### ISSUE TITLE
Identify headings by alignment

### ISSUE THREAD

**Issue by szacchino** [Krasjet/pdf.tocgen#7]
Hi,
is there a way to identify headings by paragraph alignment? In some documents, the font is always the same (both for name and size) and the bold weight is used both in paragraphs and headings. One way to distinguish between paragraphs and headings could be the alignment. 

Based on the documentation the meta information we have is just the position of the bounding box: there is a way to get all boxes with, for instance, left margin between a range of values? Or maybe in which right and left margin are equal? Or select all bold text starting from the left margin (in case we have headings with left alignment)?

Thank you for your excellent work!

**Comment by Krasjet** [comment]
`bbox.left` should ideally capture the left margin of the title.

```
y
^     +-------------+
|     | title       |
|     +-------------+
|
+-----|-----------------> x (coords might be inverted)
   bbox.left
```

Adding a restriction on it should let the filter recognize any text with the same indentation. Note that any missing attributes will be ignored for matching.

```toml
[[heading]]
level = 1
bbox.left = 293
```

If you want to set a range, use the `bbox.tolerance` field:

```toml
[[heading]]
level = 1
# match 293±1
bbox.left = 293
bbox.tolerance = 1
```
