### ISSUE TITLE
Headings of the same level getting merged into 1 line

### ISSUE THREAD

**Issue by Chalanxe** [Krasjet/pdf.tocgen#8]
For example:
```
"Part A: The Statement of Financial Position" 8
    "Usefulness Limitations Classification of Elements" 8
        "Assets Liabilities Shareholders’ Equity Concept Review Exercise: Statement of Financial Position Classification" 8
```
when it should be
```
Part A: The Statement of Financial Position
        Usefulness
        Limitations
        Classification of Elements
                Assets
                Liabilities
                Shareholders’ Equity
                Concept Review Exercise: Statement of Financial Position Classification
```

Those headings getting merged have the same info generated with the only exception of the bbox.top and bbox.bottom values.Any idea of how i should classify?

The original content page in the file also does not have any page numbers shown which might have caused this problem too..

**Comment by Krasjet** [comment]
There is no way to automatically fix it except for manual editing, though I don't think you are using `pdftocgen` correctly. It's supposed to extract titles from the main text, not the contents page. You might want to try again using the styles from main text titles.

**Comment by Krasjet** [comment]
I'll close this issue for now since this isn't bug.
