### ISSUE TITLE
Installation using pip3 not working

### ISSUE THREAD

**Issue by mandarm** [Krasjet/pdf.tocgen#9]
I'm probably doing something wrong, because I can see the project homepage at PyPI, but `pip3 install` does not work for me:

    $ pip3 --version
    pip 21.3.1 from /home/xxx/.local/lib/python3.6/site-packages/pip (python 3.6)
    $ pip3 install pdf.tocgen
    Defaulting to user installation because normal site-packages is not writeable
    ERROR: Could not find a version that satisfies the requirement pdf.tocgen (from versions: none)
    ERROR: No matching distribution found for pdf.tocgen

Any pointers would be very helpful. Thanks very much!

**Comment by Krasjet** [comment]
I'll close this issue for now since the solution is quite obvious.
